name: Continuous Integration
env:
  DOTNET_VERSION: 10.x
  SOLUTION_PATH: Backend/InventoryManagentSystemWebApi1.sln

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup workflow
        uses: actions/checkout@v4

      - name: Setup dotnet 
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run:  dotnet restore ${{ env.SOLUTION_PATH }}

      -  name: Build
         run:  dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      -  name: Run tests
         run:  dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release  --logger "trx;LogFileName=results.xml"

      -  name: Upload test results
         uses: actions/upload-artifact@v4
         if: always()
         with:
          name: test-results
          path: "**/*.trx"

