name: Continuous Integration
env:
  DOTNET_VERSION: 10.x
  SOLUTION_PATH: Backend/InventoryManagentSystemWebApi1.sln
  TESTS_FOLDER_PATH: Backend/Tests/

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup workflow
        uses: actions/checkout@v4

      - name: Setup dotnet 
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run:  dotnet restore ${{ env.SOLUTION_PATH }}

      -  name: Build
         run:  dotnet build ${{ env.SOLUTION_PATH }} --no-restore

      -  name: Run unit tests
         run:  dotnet test ${{ env.TESTS_FOLDER_PATH }}Application.Tests1 --no-build --logger "trx;LogFileName=unit_results.trx"

      - name: Run Integration tests
        run:  dotnet test ${{ env.TESTS_FOLDER_PATH }}Application.IntegrationTests --no-build --logger "trx;LogFileName=Integration_results.trx"

      -  name: Upload test results
         uses: actions/upload-artifact@v4
         if: always()
         with:
          name: test-results
          path: "**/*.trx"



